services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendar_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - app


volumes:
  db-data:
